apiVersion: apps/v1
kind: Deployment

metadata:
  name: bms-deployment
  labels:
    app: bms

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bms

  template:
    metadata:
      labels:
        app: bms

    spec:
      containers:
      - name: bms-container
        image: vipparlasandeepcharan/bms:v3

        ports:
        - containerPort: 80


